import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { classes } from "@/utils";

export default function Home() {
  return (
    <>
      <Head>
        <title>Resume | Tyler Goodwin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={classes(styles.info)}>
          <h1>Tyler Goodwin</h1>
          <p>Software Engineer | Tech Lead</p>
        </div>
      </div>
    </>
  );
}
